CREATE TABLE CLIENTE
(
  NOMBRE VARCHAR(30) NOT NULL,
  DIRECCION VARCHAR(40) NOT NULL,
  TELEFONO INT NOT NULL,
  DNI VARCHAR(20) NOT NULL,
  CODIGO_UNICO INT NOT NULL,
  PRIMARY KEY (CODIGO_UNICO)
);

CREATE TABLE RESERVA
(
  FECHA_INICIO DATE NOT NULL,
  FINAL_RESERVA DATE NOT NULL,
  NUMERO_ID INT NOT NULL,
  PRECIO_TOTAL INT NOT NULL,
  CODIGO_UNICO INT NOT NULL,
  PRIMARY KEY (NUMERO_ID),
  FOREIGN KEY (CODIGO_UNICO) REFERENCES CLIENTE(CODIGO_UNICO)
);

CREATE TABLE VEHICULO
(
  MODELO VARCHAR(30) NOT NULL,
  COLOR VARCHAR(15) NOT NULL,
  MARCA VARCHAR(20) NOT NULL,
  MATRICULA INT NOT NULL,
  PRECIO_POR_HORA INT NOT NULL,
  PRIMARY KEY (MATRICULA)
);

CREATE TABLE DE (
    LITRO_GASOLINA INT NOT NULL,
    NUMERO_ID INT NOT NULL,
    MATRICULA INT NOT NULL,
    PRIMARY KEY (NUMERO_ID , MATRICULA),
    FOREIGN KEY (NUMERO_ID)
        REFERENCES RESERVA (NUMERO_ID),
    FOREIGN KEY (MATRICULA)
        REFERENCES VEHICULO (MATRICULA)
);